[package]
name = "escrow"
version = "0.1.0"
description = "Escrow week_2_assignment"
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "escrow"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = { version = "1.2.0", features = ["init-if-needed"] }
anchor-spl = "1.2.0"

[dev-dependencies]
litesvm = "0.16.0"
litesvm-token = "0.16.0"
# you should not need to care about the dependency compatibility
solana-awesome = { version = "0.1.0", features = [
  "pubkey",
  "keypair",
  "signer",
  "message",
  "transaction",
] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(target_os, values("solana"))',
] }
