skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "4athVTb9MzXtknSnuywhYJAAudHV2SfMqZTVuVqgDWJ1"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo nextest run"

[hooks]
